export const lightTheme = {
  token: {
    colorPrimary: "#666cff",
    colorBgLayout: "#f7f7f9",
    colorBorder: "#e5e6e8",
    fontFamily: "Poppins, sans-serif",
    colorText: "#3b4056",
    colorTextSecondary: "#6e7191",
    colorBgContainer: "#ffffff",
    colorBgElevated: "#ffffff",
    colorTextPlaceholder: "#a0a3bd",
    activeBorderColor: "#666cff",
    borderRadius: 6,
  },
  components: {
    Layout: {
      headerBg: "#f7f7f9",
      siderBg: "#ffffff",
      bodyBg: "#f7f7f9",
      lightSiderBg: "#ffffff",
      headerPadding: "0 20px",
    },
    Button: {
      algorithm: true,
      primaryShadow: "none",
    },
    Table: {
      headerBg: "#f7f7f9",
      headerColor: "#3b4056",
      borderColor: "#e5e6e8",
      rowHoverBg: "#f0f0f5",
    },
    Card: {
      colorBgContainer: "#ffffff",
      headerBg: "#ffffff",
    },
    Menu: {
      itemBg: "transparent",
      itemSelectedBg: "#666cff",
      itemSelectedColor: "#ffffff",
      borderRadius: 8,
      itemHoverBg: "#f0f0f5",
      itemHoverColor: "#3b4056",
      itemActiveBg: "#f0f0f5",
      iconSize: 16,
    },
    Tooltip: {
      colorBgSpotlight: "#666cff",
    },
    Switch: {
      colorPrimary: "#52c41a",
      colorPrimaryHover: "#95de64",
      colorBgContainer: "#ff0000",
    },
    Input: {
      controlOutline: "rgba(102, 108, 255, 0.2)",
    },
    Select: {},
    DatePicker: {},
  },
};

export const darkTheme = {
  token: {
    colorPrimary: "#666cff",
    colorBgLayout: "#282a42",
    colorBgContainer: "#30334e",
    colorBgElevated: "#3f4261",
    colorText: "#d7d8ed",
    colorTextSecondary: "#8181a4",
    colorBorder: "#464963",
    fontFamily: "Poppins, sans-serif",
    colorTextPlaceholder: "#91919fc8",
    activeBorderColor: "#666cff",
    borderRadius: 6,
  },
  components: {
    Layout: {
      headerBg: "#282a42",
      siderBg: "#212235",
      bodyBg: "#282a42",
      lightSiderBg: "#212235",
      headerPadding: "0 20px",
    },
    Button: {
      algorithm: true,
    },
    Table: {
      headerBg: "#3a3e5b",
      headerColor: "#d7d8ed",
      borderColor: "#464963",
      rowHoverBg: "#3f4261",
    },
    Card: {
      colorBgContainer: "#30334e",
      headerBg: "#30334e",
    },
    Menu: {
      itemBg: "transparent",
      itemSelectedBg: "#666cff",
      itemSelectedColor: "#ffffff",
      colorSubMenuBg: "#232437",
      borderRadius: 8,
      popupBg: "#232437",
      itemHoverBg: "#3a3e5b",
      itemHoverColor: "#d7d8ed",
      itemActiveBg: "#3a3e5b",
      iconSize: 16,
    },
    Modal: {
      headerBg: "#282a42",
      contentBg: "#282a42",
    },
    Input: {
      colorBgContainer: "#30334e",
      colorBorder: "#464963",
      activeBorderColor: "#666cff",
      hoverBorderColor: "#666cff",
      controlOutline: "rgba(102, 108, 255, 0.2)",
    },
    InputNumber: {
      colorBgContainer: "#30334e",
      colorBorder: "#464963",
      activeBorderColor: "#666cff",
      hoverBorderColor: "#666cff",
      controlOutline: "rgba(102, 108, 255, 0.2)",
    },
    Select: {
      selectorBg: "#30334e",
      colorBgContainer: "#30334e",
      colorBorder: "#464963",
      optionSelectedBg: "#3a3e5b",
      optionSelectedColor: "#666cff",
      controlItemBgActive: "#3a3e5b",
      controlItemBgHover: "#686fbb",
      controlOutline: "rgba(102, 108, 255, 0.2)",
    },
    Tooltip: {
      colorBgSpotlight: "#666cff",
    },
    Switch: {
      colorPrimary: "#52c41a",
      colorPrimaryHover: "#95de64",
      colorBgContainer: "#ff0000",
    },
    DatePicker: {
      colorBgContainer: "#30334e",
      colorBorder: "#464963",
      cellActiveWithRangeBg: "rgba(102, 108, 255, 0.2)",
      controlOutline: "rgba(102, 108, 255, 0.2)",
    },
    Steps: {
      colorPrimary: "#666cff",
      navArrowColor: "#8181a4",
      colorTextDescription: "#8181a4",
    },
    Skeleton: {
      gradientFromColor: "rgba(255, 255, 255, 0.1)",
      gradientToColor: "rgba(255, 255, 255, 0.3)",
    },
  },
};
